### ISSUE TITLE
Upgrade package in composer to the latest version

### ISSUE THREAD

**Issue by FnTm** [enlitepro/enlite-monolog#4]
Hi! 

I followed the instructions to install this package via Composer and although it is operational, there are a couple of missing features. For example, in the `1.1.0` version there is no support for processors. 

Even though the same could be achieved by just putting an appropriate commit hash in the composer.json file, I think that a package update should be performed.

**Comment by julillosamaral** [comment]
I agree, I have the same problem with the versions of the package.

**Comment by lzerma** [comment]
Same here!

**Comment by abacaphiliac** [comment]
hey all,

i think i've addressed the issue with the following merge request (among other things):
https://github.com/enlitepro/enlite-monolog/pull/10/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R17

`\Monolog::getProcessors()` was added in `1.10`. automated tests pass with that version after `composer up --prefer-lowest` and after `composer up`, so i think it's the correct change.

i've submitted a couple more merge requests about code coverage, which can give greater confidence in the changes to dependency versions.

**Comment by cubanec** [comment]
Fixed in https://github.com/enlitepro/enlite-monolog/pull/17
