### ISSUE TITLE
EnliteMonolog is vulnerable to handlers order

### ISSUE THREAD

**Issue by szoper** [enlitepro/enlite-monolog#7]
There is no information regarding peculiarity of handlers order in the documentation.
Consider this example:

```
return [
    'EnliteMonolog' => array(
        'log'       => array(
            'name'     => 'log',
            'handlers' => array(
                'default' => array(
                    'name'      => 'Monolog\Handler\SyslogHandler',
                    'args'      => array(
                        'ident'    => SYSLOG_IDENT,
                        'facility' => LOG_LOCAL2,
                    ),
                    'formatter' => array(
                        'name' => 'Monolog\Formatter\LineFormatter',
                    ),
                ),
                'hipchat' => array(
                    'name' => 'Monolog\Handler\NullHandler',
                ),
            ),
        ),
```

First handler is using syslog, the latter is null (just a placeholder for other app environments).
`\EnliteMonolog\Service\MonologServiceFactory::createLogger` reverses the handlers array, so for Monolog, handlers look like:

```
array(
  0 => 'NullHandler',
  1 => 'SyslogHandler',
);
```

what, with conjuction with below code in `\Monolog\Logger::addRecord`

```
        foreach ($this->handlers as $key => $handler) {
            if ($handler->isHandling(array('level' => $level))) {
                $handlerKey = $key;
                break;
            }
        }
```

results with NullHandler being chosen and no log message being logged at all.

The ultimate solution would be not to `pushHandler` in MonologServiceFactory but to `setHandlers`.
If that change is not possible, please at least write about in the docs.

**Comment by snapshotpl** [comment]
I think is already fixed @Sysaninster
